### ISSUE TITLE
Metadata import in GeoNode

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/oaw-georectify-process-airflow#10]
During the import stage (form the airflow workflow) we need to read metadata information and then publish them with the raster image.

**Comment by chpicone** [comment]
We are ready to update the Airflow GeoNode Upload Operator to add metadata information.
New version of our geotiflib (from master) is now able to read XMP information and then store them as items in the GDAL_metadata section.
A method from the geotif class can provide a dictionary with the required information.
```
**Geonode** 						**Tifftags_DC**								
TITLE							Title				
Date							Date (YYYY)					
Edition							???								
Abstract						Description							
Purpose							Source (URL)					
Free-text Keywords					Subject						
Supplemental information 				Relation								
Data quality statement 					Format								
Typename						Identifier
```
The method **oaw_metadata_dict** return a dictionary containing the following keys:
- creator (not necessary at the moment)
- date
- description
- format
- identifier
- relation
- source
- subject
- title
- edition

**Comment by chpicone** [comment]
Here an example of the usage:
https://github.com/geosolutions-it/oaw-georectify-process-alg/blob/c9b64011a415008de31791cfa90c061d85559fa4/tests/test_geotiff.py#L236

**Comment by chpicone** [comment]
I am asking the customer to understand for the field "Free-text Keywords" if we have to split the string contained in the OAW_SUBJECT field by the ";" character.

**Comment by chpicone** [comment]
Customer is using **hierarchical keywords** so the ";" character separates words in different hirarchical levels:
![image](https://user-images.githubusercontent.com/2872823/116423448-fe22d100-a840-11eb-9655-64b5e872a83a.png)

@mattiagiupponi we need to ask someone of the GeoNode group if it is possible to call the rest api in someway for this purpose.

**Comment by mattiagiupponi** [comment]
Regarding the metadata upload, looks like that the XML file is the best approach from a GeoNode perspective.
In few words:
1. convert the metadata extracted by the library from JSON to XML
2. in the OAW GeoNode project  (https://github.com/geosolutions-it/oaw-geonode) write a custom metadata parser to handle the metadata sent by the API with a custom parser ( GNIP: https://github.com/GeoNode/geonode/issues/7263 DOC: https://docs.geonode.org/en/master/basic/settings/index.html?#metadata-parsers ) already available on the master branch

**Comment by mattiagiupponi** [comment]
At the moment the metadata are mapped in this way:
```python
{    
    "title": metadata.get('title', None),
      "date": metadata.get('date', None),
     "edition":  metadata.get('edition', None),
     "abstract": metadata.get('description', None),
     "purpose": metadata.get('source', None),
     "keywords": [k.replace(' ', '') for k in metadata.get('subject', None).split(';')],
     "supplemental_information":  metadata.get('relation', None),
     "data_quality_statement": metadata.get('format', None),
     "typename": metadata.get('identifier', None),
}
```
