### ISSUE TITLE
OAW: Document the Airflow module

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/oaw-georectify-process-airflow#18]
We need to add a section in this document:
https://docs.google.com/document/d/1px8MAlC--9sZrWJ26aicxFWXxbrDeX-m0v1KE_VHCOA/edit#heading=h.hpvkr3wxmvs0
to:
- explain how to configure/update variables used in the Georectify DAGs
- explain how to configure/update connection parameter to GeoNode
- minimal explanation of the UI of Airflow
- explain how to check problem with a failing task (via  the log button)
- explain how to re-run a failed DAG

**Comment by mattiagiupponi** [comment]
- [ ] explain how to configure/update variables used in the Georectify DAGs
- [ ] explain how to configure/update connection parameter to GeoNode
- [ ] minimal explanation of the UI of Airflow
- [ ] explain how to check problem with a failing task (via the log button)
- [ ] explain how to re-run a failed DAG

**Comment by mattiagiupponi** [comment]
@chpicone documentation updated https://docs.google.com/document/d/1px8MAlC--9sZrWJ26aicxFWXxbrDeX-m0v1KE_VHCOA/edit#heading=h.7rck0m39aknu
Please takes few minutes for a review

**Comment by chpicone** [comment]
@mattiagiupponi can you add a little section explaining how to configure max number of concurrent DAGs execution?

**Comment by mattiagiupponi** [comment]
@chpicone I made some changes into the document. Please takes some minutes to review the "Dag settings" paragraph
